services:
  - type: web
    name: mi-aplicacion
    env: docker
    buildCommand: ''
    startCommand: ''
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    plan: free
    branches: ["main"]
    envVars:
      - key: PORT
        value: "10000"
    exposePort: 10000
