services:
  - type: web
    name: mi-aplicacion
    env: docker
    buildCommand: ''
    startCommand: ''
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    plan: free
    envVars:
      - key: PORT
        value: "10000"
